Tweak Cloud Java client configs for better behavior
confluentinc/configuration-templates pull request #6
Opened 2020-05-31 15:55 UTC by ijuma

- Add acks=all to avoid data loss during kafka rolls
- Add linger.ms=5 to improve batching with nearly no impact to latency
- Remove ssl.endpoint.identification.algorithm since matches the default
since Apache Kafka 2.0 and it's not strictly required (i.e. things
work without it).

2020-05-31 15:57 UTC, ijuma commented
`linger.ms=5` is perhaps a bit controversial as it's not strictly required, but it would be good to encourage better behavior by default.

2020-05-31 15:57 UTC, ijuma commented
cc @gwenshap @ybyzek @lbradstreet @hachikuji

2020-05-31 15:59 UTC, gwenshap commented
linger.ms=5 is also inline with our tuning recommendations (3 different blog posts, I believe).

2020-05-31 15:59 UTC, ijuma commented
Once we agree on this PR, I'll submit another PR for https://docs.confluent.io/current/cloud/using/config-client.html

2020-05-31 16:26 UTC, ijuma commented
Submitted https://github.com/confluentinc/docs/pull/4730

2020-05-31 16:58 UTC, lbradstreet commented
I'm good with `linger.ms=5` given everything we've discussed. These seem to be generic client configs, so I assume they will be supplied to consumers often too? From what I remember that will result in warnings but not errors.

2020-05-31 17:02 UTC, ijuma commented
Good point, that's a bit annoying. Hmm.

2020-05-31 23:00 UTC, mhowlett commented
when perf testing of the python client I arrived at ~5ms being about optimal. I found a big increase in throughput up to about 5ms, and it tapered of significantly after. Furthermore, with serious workloads, 5ms gives lower latency than 0ms due to fewer broker requests. I think 5ms is a great default and 0ms is hard to defend as being good.

2020-06-03 18:12 UTC, lbradstreet commented
Should we consider setting `client.dns.lookup = "use_all_dns_ips"` in these configs? We will be changing the default in our clients, but users may use older clients for some time. I think it's reasonable to set this specifically in the configs that we provide to our customers as it isn't a breaking change if they specifically copy our config into their clients.

2020-10-02 15:12 UTC, ybyzek requested changes
FYI this repo is deprecated, please see README.

So this PR will not propagate to Confluent Cloud or docs or examples.

2020-10-02 15:14 UTC, ijuma commented
Thanks for the heads up. I will submit a PR to the new one.

2020-10-02 15:14 UTC, closed without merging

2020-10-02 15:21 UTC, ijuma commented
@ybyzek https://github.com/confluentinc/examples/pull/820

2020-10-02 16:00 UTC, ybyzek commented
Thanks @ijuma !